name: finease
description: "A full stack mobile app to keep track of financial transactions"
publish_to: 'none'
version: 1.2.9

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  currency_picker: 2.0.20
  dynamic_color: 1.6.9
  file_picker: ^10.0.0
  fl_chart: 0.66.0
  flutter:
    sdk: flutter
  go_router: 13.1.0
  google_fonts: 6.1.0
  hive: 2.2.3
  http: ^1.2.0
  intl: 0.17.0
  local_auth: 2.1.8
  material_design_icons_flutter: 7.0.7296
  package_info_plus: ^8.3.0
  password_strength: 0.2.0
  path: 1.9.1
  path_provider: 2.1.2
  pointycastle: 3.7.4
  provider: ^6.1.5+1
  responsive_builder: 0.7.0
  share_plus: 7.0.2
  sqflite: 2.4.2
  url_launcher: 6.2.3
  win32: ^5.12.0
  xml: 6.5.0

dev_dependencies:
  flutter_lints: 3.0.1
  test: ^1.25.15

flutter:
  uses-material-design: true
